#!/usr/bin/env python3
"""Resolve the Google gs101 manifest's branch names to immutable commits."""

from __future__ import annotations

import argparse
import base64
import subprocess
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path


def resolve_ref(repo_url: str, revision: str) -> str:
    if len(revision) == 40 and all(ch in "0123456789abcdef" for ch in revision):
        return revision
    output = subprocess.check_output(
        ["git", "ls-remote", repo_url, f"refs/heads/{revision}"],
        text=True,
        timeout=120,
    ).strip()
    if not output:
        raise RuntimeError(f"cannot resolve {repo_url} branch {revision}")
    commit = output.split()[0]
    if len(commit) != 40:
        raise RuntimeError(f"unexpected ref from {repo_url}: {output}")
    return commit


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    pins: dict[str, str] = {}
    with (project_root / "config" / "pins.env").open() as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            pins[key] = value

    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest-ref", default=pins["GOOGLE_MANIFEST_REF"])
    parser.add_argument("--common-ref", default=pins["COMMON_KERNEL_REF"])
    parser.add_argument(
        "--output",
        type=Path,
        default=project_root / "config" / "manifest-lock.xml",
    )
    args = parser.parse_args()

    manifest_url = (
        f"{pins['GOOGLE_MANIFEST_REPO']}/+/{args.manifest_ref}/default.xml?format=TEXT"
    )
    encoded = urllib.request.urlopen(manifest_url, timeout=120).read()
    manifest_xml = base64.b64decode(encoded)
    root = ET.fromstring(manifest_xml)
    default = root.find("default")
    if default is None:
        raise RuntimeError("manifest has no <default>")
    default_revision = default.attrib["revision"]
    remote_nodes = {node.attrib["name"]: node for node in root.findall("remote")}

    output_root = ET.Element("manifest")
    output_root.append(ET.Comment("Generated by scripts/lock-manifest.py; review before committing."))
    for project in root.findall("project"):
        project_path = project.attrib["path"]
        project_name = project.attrib["name"]
        revision = project.attrib.get("revision", default_revision)
        if project_path == "common":
            resolved = args.common_ref
        else:
            remote_name = project.attrib.get("remote", default.attrib.get("remote"))
            remote = remote_nodes.get(remote_name or "")
            fetch = remote.attrib.get("fetch", "") if remote is not None else ""
            if not fetch.startswith("http"):
                fetch = "https://android.googlesource.com/"
            repo_url = f"{fetch.rstrip('/')}/{project_name}"
            resolved = resolve_ref(repo_url, revision)
        ET.SubElement(
            output_root,
            "extend-project",
            path=project_path,
            name=project_name,
            revision=resolved,
        )

    ET.indent(output_root, space="  ")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        + ET.tostring(output_root, encoding="unicode")
        + "\n"
    )
    print(f"wrote {len(root.findall('project'))} project pins to {args.output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, subprocess.SubprocessError) as error:
        print(f"lock generation failed: {error}", file=sys.stderr)
        raise SystemExit(1)
